
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_vue_filament_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: mysql:8
    platform: linux/arm64
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_filament_vue_db
      MYSQL_USER: laravel_filament_vue_usr
      MYSQL_PASSWORD: laravel_filament_vue_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  nginx:
    image: nginx:latest
    platform: linux/arm64
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data:
